### ISSUE TITLE
Is Linux supported?

### ISSUE THREAD

**Issue by hcji** [MatteoLacki/opentims_bruker_bridge#1]
Hi,

Thanks for your great work, I wonder can I use this package on Linux?

Best

**Comment by MatteoLacki** [comment]
Yes, it works on Linux.
Have a look at: https://github.com/michalsta/opentims
for more details.

Best wishes,

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by hcji** [comment]
Thanks for your reply
