### ISSUE TITLE
libtimsdata.so: invalid ELF header

### ISSUE THREAD

**Issue by jorainer** [MatteoLacki/opentims_bruker_bridge#2]
Hi,

we're working on an integration of the `opentimsr` library and TimsTOF files into the [`Spectra`](https://github.com/RforMassSpectrometry/Spectra) MS infrastructure (specifically using the [MsBackendTimsTof](https://github.com/rformassspectrometry/MsBackendTimsTof) package). Somehow the magic auto-downloader of the so file seems to not working properly:

```r
> so_folder <- tempdir()
> library(opentimsr)
> so_file <- download_bruker_proprietary_code(so_folder)
[1] "Welcome to a real OS."
[1] "Downloading from: https://github.com/MatteoLacki/opentims_bruker_bridge/raw/main/opentims_bruker_bridge/libtimsdata.so"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   177  100   177    0     0    648      0 --:--:-- --:--:-- --:--:--   648
> setup_bruker_so(so_file)
Error in .setup_bruker_so(path) : 
  dlopen(/tmp/Rtmpii5JIS/libtimsdata.so) failed, reason: /tmp/Rtmpii5JIS/libtimsdata.so: invalid ELF header
```

The size of the downloaded file is also only 177 bytes, which makes no sense - I got another one from Bruker which is > 20MB large.

**Comment by jorainer** [comment]
Update: seems there is some issue with option `method = "curl"`. It works if I use `download_bruker_proprietary_code(so_folder, method = "wget")` or `download_bruker_proprietary_code(so_folder, method = "libcurl")`.

**Comment by michalsta** [comment]
Okay, so it appears method="curl" can't handle HTTP/302 (redirect). Well, the fix is rather straightforward: provide a direct link in opentimsr sources. I'll put a fixed package on CRAN, in the meantime feel free to use other, smarter download methods ;)

**Comment by jorainer** [comment]
Thanks!
